### ISSUE TITLE
Illegal inferred equivalence

### ISSUE THREAD

**Issue by matentzn** [oral-health-and-disease-ontologies/ohd-ontology#90]
when running:

```
robot --catalog catalog-v001.xml reason --input ohd-edit.owl --reasoner ELK --equivalent-classes-allowed asserted-only --exclude-tautologies structural --output test.owl
```

We get:

```
2023-07-12 12:40:49,210 ERROR org.obolibrary.robot.ReasonOperation - Only equivalent classes that have been asserted are allowed. Inferred equivalencies are forbidden.
2023-07-12 12:40:49,212 ERROR org.obolibrary.robot.ReasonOperation - Equivalence: <http://purl.obolibrary.org/obo/OHD_0000235> == <http://purl.obolibrary.org/obo/OHD_0000225>
```

Which is not allowed as per ODK standards; 

@wdduncan can you fix this in Protege? You can do it on a separate branch.

**Comment by wdduncan** [comment]
The classes [restored labial surface](http://purl.obolibrary.org/obo/OHD_0000225) and [restored facial surface](http://purl.obolibrary.org/obo/OHD_0000235) are (in fact) the same. The equivalence assertion was intentional. 

A bit of history ...   
The situation is bit aggravating. Many text books call it the "labial surface" (which I think is the original term), while many electronic systems refer to it as the "facial surface". The reason for "facial" is that many electronic record systems use the first letter of the surface to indicate which surfaces were restored. For example, a record of having "MO" restored means the mesial and occlusal  surfaces of the tooth were restored.

However, there is another tooth surface called the "lingual" surface. So, if a record say that surfaces "MOL" were restored, it is ambiguous whether the "L" refers to the lingual or labial surface. To address this, practitioner/EMR vendors use "facial" instead of "labial".

Instead of using an annotation to note the synonymity between "facial" and "lingual", the decision was made (I can't recall why), to assert two equivalence.
  
Moving forward ...  
I can (of course) obsolete one of the classes (most likely "labial surface") and add an `oboInOwl:has exact synonym` annotation. I do not know if this the agreed upon annotation to use for such cases. OMO  is a bit of moving target, and I've stopped (due to lack of time) trying to keep up with it.  (BTW, the `oboInOwl` APs were only recently added.)

The other option is to leave it as is. What are the draw backs?

@gopi-kris You may find this discussion interesting.

**Comment by matentzn** [comment]
I think your solution with adding and exact synonym is exactly the correct one. You don't want to ever have 2 classes (irrespective of their labels) that refer to the same concept in the same namespace - that is just bad practice, and creates all sorts of churns (and ugly class hierarchies).

Would you be able to do the obsolete, synonym solution?

**Comment by wdduncan** [comment]
> Would you be able to do the obsolete, synonym solution?  

Yes    

> You don't want to ever have 2 classes (irrespective of their labels) that refer to the same concept 

You are sounding like a BFO realist now :)

> that is just bad practice, and creates all sorts of churns (and ugly class hierarchies).   

I think that statement is quite argumentative :)      

ODK (or OBO) standards are not always as authoritative as they  claim to be. There are plenty of ontologies that are very successful (e.g. SNOMED, NCIT), and do not necessarily adhere to such standards.   

I could make a case for leaving the classes in the OHD.  However, I don't much benefit in arguing my case.

**Comment by gopi-kris** [comment]
We can model this in this way as well. The facial surfaces are the surfaces on the outside of the teeth. There are 2 subclasses of facial surfaces depending on the location of the teeth. If the teeth are in the anterior sextant the facial surface is called a Labial surface, as in Labia or Lips (or near lips). If the teeth are in the posterior sextant, the facial surface is called a Buccal surface, as in near to cheeks. This is for both upper and lower arches.

For more information on sextants see the image below:
[https://www.researchgate.net/profile/Riemer-Slart/publication/343846256/figure/fig1/AS:930139131113472@1598773858676/Oral-cavity-divided-into-six-sextants-Sextant-segment-1-upper-right-premolar-molar_Q320.jpg](url)

For more information on facial surfaces see the image below:
[https://cdeworld.com/media/23170](url)

The tooth surfaces near the tongue are called Lingual (as in near the tongue). This is widely used for both upper and lower arches.

However, I have also seen dentists use the term Palatal (as in near the Palate) to describe the lingual surfaces of teeth of the upper arch and only use the term Lingual to describe the lingual surfaces of the teeth in the lower arch. This makes sense since the Palate is in the upper jaw and the Tongue is in the lower jaw. I don't think this is very common here in the US.

EMR/EDR vendors may use different acronyms to differentiate between Labial and Lingual surfaces. However, they are accurate to call in Facial as it can include Labial and Buccal surfaces. Ideally, we would want to annotate Labial and Buccal surfaces separately.

**Comment by wdduncan** [comment]
> However, they are accurate to call in Facial as it can include Labial and Buccal surfaces

Yes, 'facial' may refer to the both the buccal and labial surfaces. However, in the EMRs I've worked with, buccal and facial/labial surfaces have been represented using 'B' and 'F', with 'F' meaning the labial surface. Was it different to Marquette?

> I have also seen dentists use the term Palatal (as in near the Palate) to describe the lingual surfaces of teeth of the upper arch and only use the term Lingual to describe the lingual surfaces of the teeth in the lower arch.

Interesting! I hadn't ran across this yet :)

**Comment by gopi-kris** [comment]
@wdduncan, it's possible EMR vendors in the US are following the ADA CDT terminology for dental insurance claims. See attached. I don't remember how it was at Marquette, most likely the same methods are used across all Axium implementations.

![ADA Dental Claim Form Completion Instructions - Tooth surfaces](https://github.com/oral-health-and-disease-ontologies/ohd-ontology/assets/47677575/f0ac4ec3-c281-4b3d-bba1-abc8e801a6e0)
Source: ADA Dental Claim Form Completion Instructions - Version 2019 - Page 10.

I've seen the term Facial being used to describe both Labial and Buccal surfaces in some systems AND only labial surfaces in other systems. However, I think using the term Facial to describe only Labial surfaces is incorrect and a bit redundant. I also don't think this is what is being taught to students. For example, see attached screenshots from Wheeler's Dental Anatomy, Physiology and Occlusion -  10th Edition, which is a recommended basic dental anatomy textbook for dental students. 

![Wheeler's Dental](https://github.com/oral-health-and-disease-ontologies/ohd-ontology/assets/47677575/81be1b91-9574-46b9-8ff7-98ce9574ba09)

![Wheeler's Dental text](https://github.com/oral-health-and-disease-ontologies/ohd-ontology/assets/47677575/518c9484-af98-493f-830a-700c847b0251)
